# Generated by Django 5.0.4 on 2024-05-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='massage',
            new_name='message',
        ),
    ]
