# Generated by Django 5.0.4 on 2024-06-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_product',
        ),
    ]
