# Generated by Django 5.0.4 on 2024-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0009_add_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pincode', models.IntegerField(max_length=30)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('list', models.TextField()),
            ],
        ),
    ]
