# Generated by Django 5.0.3 on 2024-06-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
